parameters:
  thrift.host: localhost
  thrift.port: 6831
  thrift.buffer.size: 4096
  opentrace.sampler.rate: 0.1
services:
  ds.stack:
    class: Ds\Stack
    shared: false
  id.generator.random:
    class: CodeTool\OpenTracing\Id\RandomIntGenerator
  id.generator.span: '@id.generator.random'
  sampler.always:
    class: CodeTool\OpenTracing\Sampler\ConstSampler
    arguments: [true]
  sampler.const:
    class: CodeTool\OpenTracing\Sampler\ConstSampler
    arguments: ['%kernel.debug%']
  sampler.probabilistic:
    class: CodeTool\OpenTracing\Sampler\ProbabilisticSampler
    arguments: ['%opentrace.sampler.rate%']
  opentrace.sampler: '@sampler.always'
  span.factory:
    class: CodeTool\OpenTracing\Span\Factory\SpanFactory
    arguments: ['@id.generator.span', '@opentrace.sampler']
  client.thrift:
    class: CodeTool\OpenTracing\Client\ThriftClient
    arguments: ['%service_name%', '@thrift.agent']
  thrift.agent:
    class: CodeTool\OpenTracing\Jaeger\Thrift\Agent\AgentClient
    arguments: ['@thrift.protocol']
  thrift.protocol.compact:
    class: Thrift\Protocol\TCompactProtocol
    arguments: ['@thrift.transport']
  thrift.protocol.binary:
    class: Thrift\Protocol\TBinaryProtocol
    arguments: ['@thrift.transport']
  thrift.protocol: '@thrift.protocol.compact'
  thrift.transport.udp:
    class: CodeTool\OpenTracing\Transport\TUDPTransport
    arguments: ['%thrift.host%', '%thrift.port%']
  thrift.transport.buffered:
    class: Thrift\Transport\TBufferedTransport
    arguments: ['@thrift.transport.udp', '%thrift.buffer.size%', '%thrift.buffer.size%']
    calls:
      -
        method: open
        arguments: []
  thrift.transport: '@thrift.transport.buffered'
  tracer:
    class: CodeTool\OpenTracing\Tracer\Tracer
    arguments: ['@ds.stack', '@span.factory', '@client.thrift']
